Feature/cmake dependencies
kamping-site/kassert pull request #48
Opened 2023-10-20 08:41 UTC by niklas-uhl

2023-10-23 21:00 UTC, kurpicz requested changes

2023-10-23 21:00 UTC, kurpicz commented on CMakeLists.txt
> +function (ensure_googletest)
Maybe we should move utility functionality like this in a different file to keep the main `CMakeLists.txt` short.

2023-10-23 21:00 UTC, kurpicz commented on CMakeLists.txt
> +# Using CMake >= 3.24 we override find_package and it "just works". For older versions we simulate the same behavior by
Can we automatically test this for different CMake versions in our GitHub action, i.e., add different CMake versions to our build matrix?

2025-02-09 17:42 UTC, mschimek approved these changes
Given my limited knowledge of CMake this looks goods

2025-02-09 21:27 UTC, merged